// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.cuixe.socket;

public final class vo {
  private vo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bmv.protobuf.messages.PingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 sendingTime = 1;</code>
     */
    long getSendingTime();

    /**
     * <code>int64 requestTime = 2;</code>
     */
    long getRequestTime();
  }
  /**
   * Protobuf type {@code com.bmv.protobuf.messages.PingRequest}
   */
  public  static final class PingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bmv.protobuf.messages.PingRequest)
      PingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingRequest.newBuilder() to construct.
    private PingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingRequest() {
      sendingTime_ = 0L;
      requestTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sendingTime_ = input.readInt64();
              break;
            }
            case 16: {

              requestTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cuixe.socket.vo.PingRequest.class, com.cuixe.socket.vo.PingRequest.Builder.class);
    }

    public static final int SENDINGTIME_FIELD_NUMBER = 1;
    private long sendingTime_;
    /**
     * <code>int64 sendingTime = 1;</code>
     */
    public long getSendingTime() {
      return sendingTime_;
    }

    public static final int REQUESTTIME_FIELD_NUMBER = 2;
    private long requestTime_;
    /**
     * <code>int64 requestTime = 2;</code>
     */
    public long getRequestTime() {
      return requestTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sendingTime_ != 0L) {
        output.writeInt64(1, sendingTime_);
      }
      if (requestTime_ != 0L) {
        output.writeInt64(2, requestTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sendingTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sendingTime_);
      }
      if (requestTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cuixe.socket.vo.PingRequest)) {
        return super.equals(obj);
      }
      com.cuixe.socket.vo.PingRequest other = (com.cuixe.socket.vo.PingRequest) obj;

      boolean result = true;
      result = result && (getSendingTime()
          == other.getSendingTime());
      result = result && (getRequestTime()
          == other.getRequestTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDINGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendingTime());
      hash = (37 * hash) + REQUESTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cuixe.socket.vo.PingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cuixe.socket.vo.PingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bmv.protobuf.messages.PingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bmv.protobuf.messages.PingRequest)
        com.cuixe.socket.vo.PingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cuixe.socket.vo.PingRequest.class, com.cuixe.socket.vo.PingRequest.Builder.class);
      }

      // Construct using com.cuixe.socket.vo.PingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sendingTime_ = 0L;

        requestTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingRequest_descriptor;
      }

      public com.cuixe.socket.vo.PingRequest getDefaultInstanceForType() {
        return com.cuixe.socket.vo.PingRequest.getDefaultInstance();
      }

      public com.cuixe.socket.vo.PingRequest build() {
        com.cuixe.socket.vo.PingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cuixe.socket.vo.PingRequest buildPartial() {
        com.cuixe.socket.vo.PingRequest result = new com.cuixe.socket.vo.PingRequest(this);
        result.sendingTime_ = sendingTime_;
        result.requestTime_ = requestTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cuixe.socket.vo.PingRequest) {
          return mergeFrom((com.cuixe.socket.vo.PingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cuixe.socket.vo.PingRequest other) {
        if (other == com.cuixe.socket.vo.PingRequest.getDefaultInstance()) return this;
        if (other.getSendingTime() != 0L) {
          setSendingTime(other.getSendingTime());
        }
        if (other.getRequestTime() != 0L) {
          setRequestTime(other.getRequestTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cuixe.socket.vo.PingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cuixe.socket.vo.PingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sendingTime_ ;
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public long getSendingTime() {
        return sendingTime_;
      }
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public Builder setSendingTime(long value) {
        
        sendingTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public Builder clearSendingTime() {
        
        sendingTime_ = 0L;
        onChanged();
        return this;
      }

      private long requestTime_ ;
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public long getRequestTime() {
        return requestTime_;
      }
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public Builder setRequestTime(long value) {
        
        requestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public Builder clearRequestTime() {
        
        requestTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bmv.protobuf.messages.PingRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bmv.protobuf.messages.PingRequest)
    private static final com.cuixe.socket.vo.PingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cuixe.socket.vo.PingRequest();
    }

    public static com.cuixe.socket.vo.PingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingRequest>
        PARSER = new com.google.protobuf.AbstractParser<PingRequest>() {
      public PingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingRequest> getParserForType() {
      return PARSER;
    }

    public com.cuixe.socket.vo.PingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bmv.protobuf.messages.PingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 sendingTime = 1;</code>
     */
    long getSendingTime();

    /**
     * <code>int64 requestTime = 2;</code>
     */
    long getRequestTime();
  }
  /**
   * Protobuf type {@code com.bmv.protobuf.messages.PingResponse}
   */
  public  static final class PingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bmv.protobuf.messages.PingResponse)
      PingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingResponse.newBuilder() to construct.
    private PingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingResponse() {
      sendingTime_ = 0L;
      requestTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sendingTime_ = input.readInt64();
              break;
            }
            case 16: {

              requestTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cuixe.socket.vo.PingResponse.class, com.cuixe.socket.vo.PingResponse.Builder.class);
    }

    public static final int SENDINGTIME_FIELD_NUMBER = 1;
    private long sendingTime_;
    /**
     * <code>int64 sendingTime = 1;</code>
     */
    public long getSendingTime() {
      return sendingTime_;
    }

    public static final int REQUESTTIME_FIELD_NUMBER = 2;
    private long requestTime_;
    /**
     * <code>int64 requestTime = 2;</code>
     */
    public long getRequestTime() {
      return requestTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sendingTime_ != 0L) {
        output.writeInt64(1, sendingTime_);
      }
      if (requestTime_ != 0L) {
        output.writeInt64(2, requestTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sendingTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sendingTime_);
      }
      if (requestTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cuixe.socket.vo.PingResponse)) {
        return super.equals(obj);
      }
      com.cuixe.socket.vo.PingResponse other = (com.cuixe.socket.vo.PingResponse) obj;

      boolean result = true;
      result = result && (getSendingTime()
          == other.getSendingTime());
      result = result && (getRequestTime()
          == other.getRequestTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDINGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendingTime());
      hash = (37 * hash) + REQUESTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cuixe.socket.vo.PingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cuixe.socket.vo.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cuixe.socket.vo.PingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bmv.protobuf.messages.PingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bmv.protobuf.messages.PingResponse)
        com.cuixe.socket.vo.PingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cuixe.socket.vo.PingResponse.class, com.cuixe.socket.vo.PingResponse.Builder.class);
      }

      // Construct using com.cuixe.socket.vo.PingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sendingTime_ = 0L;

        requestTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cuixe.socket.vo.internal_static_com_bmv_protobuf_messages_PingResponse_descriptor;
      }

      public com.cuixe.socket.vo.PingResponse getDefaultInstanceForType() {
        return com.cuixe.socket.vo.PingResponse.getDefaultInstance();
      }

      public com.cuixe.socket.vo.PingResponse build() {
        com.cuixe.socket.vo.PingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cuixe.socket.vo.PingResponse buildPartial() {
        com.cuixe.socket.vo.PingResponse result = new com.cuixe.socket.vo.PingResponse(this);
        result.sendingTime_ = sendingTime_;
        result.requestTime_ = requestTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cuixe.socket.vo.PingResponse) {
          return mergeFrom((com.cuixe.socket.vo.PingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cuixe.socket.vo.PingResponse other) {
        if (other == com.cuixe.socket.vo.PingResponse.getDefaultInstance()) return this;
        if (other.getSendingTime() != 0L) {
          setSendingTime(other.getSendingTime());
        }
        if (other.getRequestTime() != 0L) {
          setRequestTime(other.getRequestTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cuixe.socket.vo.PingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cuixe.socket.vo.PingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sendingTime_ ;
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public long getSendingTime() {
        return sendingTime_;
      }
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public Builder setSendingTime(long value) {
        
        sendingTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendingTime = 1;</code>
       */
      public Builder clearSendingTime() {
        
        sendingTime_ = 0L;
        onChanged();
        return this;
      }

      private long requestTime_ ;
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public long getRequestTime() {
        return requestTime_;
      }
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public Builder setRequestTime(long value) {
        
        requestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTime = 2;</code>
       */
      public Builder clearRequestTime() {
        
        requestTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bmv.protobuf.messages.PingResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bmv.protobuf.messages.PingResponse)
    private static final com.cuixe.socket.vo.PingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cuixe.socket.vo.PingResponse();
    }

    public static com.cuixe.socket.vo.PingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingResponse>
        PARSER = new com.google.protobuf.AbstractParser<PingResponse>() {
      public PingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingResponse> getParserForType() {
      return PARSER;
    }

    public com.cuixe.socket.vo.PingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bmv_protobuf_messages_PingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bmv_protobuf_messages_PingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bmv_protobuf_messages_PingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bmv_protobuf_messages_PingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\031com.bmv.protobuf.messages\"" +
      "7\n\013PingRequest\022\023\n\013sendingTime\030\001 \001(\003\022\023\n\013r" +
      "equestTime\030\002 \001(\003\"8\n\014PingResponse\022\023\n\013send" +
      "ingTime\030\001 \001(\003\022\023\n\013requestTime\030\002 \001(\003B\026\n\020co" +
      "m.cuixe.socketB\002vob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bmv_protobuf_messages_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bmv_protobuf_messages_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bmv_protobuf_messages_PingRequest_descriptor,
        new java.lang.String[] { "SendingTime", "RequestTime", });
    internal_static_com_bmv_protobuf_messages_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bmv_protobuf_messages_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bmv_protobuf_messages_PingResponse_descriptor,
        new java.lang.String[] { "SendingTime", "RequestTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
